name: todo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.3.8
  flutter_local_notifications: ^8.2.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^2.1.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
